FROM python:3.12-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PYTHONUNBUFFERED=1 \
    LOG_LEVEL=INFO \
    PROM_PORT=8000

CMD ["python", "-u", "ingestor.py"]
